development:
  adapter: sqlite3
  encoding: unicode
  database: g360-event-application_development
  pool: 5
  username: g360-event-application
  password: "0000"

test:
  adapter: sqlite3
  encoding: unicode
  database: g360-event-application_test
  pool: 5
  username: g360-event-application
  password: "0000"
