development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5
  username: g360-event-application
  password: "0000"

test:
  adapter: sqlite3
  encoding: unicode
  database: db/test.sqlite3
  pool: 5
  username: g360-event-application
  password: "0000"
