require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventGiveawaysController do

  # This should return the minimal set of attributes required to create a valid
  # EventGiveaway. As you add validations to EventGiveaway, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventGiveawaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all event_giveaways as @event_giveaways" do
      event_giveaway = EventGiveaway.create! valid_attributes
      get :index, {}, valid_session
      assigns(:event_giveaways).should eq([event_giveaway])
    end
  end

  describe "GET show" do
    it "assigns the requested event_giveaway as @event_giveaway" do
      event_giveaway = EventGiveaway.create! valid_attributes
      get :show, {:id => event_giveaway.to_param}, valid_session
      assigns(:event_giveaway).should eq(event_giveaway)
    end
  end

  describe "GET new" do
    it "assigns a new event_giveaway as @event_giveaway" do
      get :new, {}, valid_session
      assigns(:event_giveaway).should be_a_new(EventGiveaway)
    end
  end

  describe "GET edit" do
    it "assigns the requested event_giveaway as @event_giveaway" do
      event_giveaway = EventGiveaway.create! valid_attributes
      get :edit, {:id => event_giveaway.to_param}, valid_session
      assigns(:event_giveaway).should eq(event_giveaway)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventGiveaway" do
        expect {
          post :create, {:event_giveaway => valid_attributes}, valid_session
        }.to change(EventGiveaway, :count).by(1)
      end

      it "assigns a newly created event_giveaway as @event_giveaway" do
        post :create, {:event_giveaway => valid_attributes}, valid_session
        assigns(:event_giveaway).should be_a(EventGiveaway)
        assigns(:event_giveaway).should be_persisted
      end

      it "redirects to the created event_giveaway" do
        post :create, {:event_giveaway => valid_attributes}, valid_session
        response.should redirect_to(EventGiveaway.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event_giveaway as @event_giveaway" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventGiveaway.any_instance.stub(:save).and_return(false)
        post :create, {:event_giveaway => {  }}, valid_session
        assigns(:event_giveaway).should be_a_new(EventGiveaway)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventGiveaway.any_instance.stub(:save).and_return(false)
        post :create, {:event_giveaway => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested event_giveaway" do
        event_giveaway = EventGiveaway.create! valid_attributes
        # Assuming there are no other event_giveaways in the database, this
        # specifies that the EventGiveaway created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EventGiveaway.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => event_giveaway.to_param, :event_giveaway => { "these" => "params" }}, valid_session
      end

      it "assigns the requested event_giveaway as @event_giveaway" do
        event_giveaway = EventGiveaway.create! valid_attributes
        put :update, {:id => event_giveaway.to_param, :event_giveaway => valid_attributes}, valid_session
        assigns(:event_giveaway).should eq(event_giveaway)
      end

      it "redirects to the event_giveaway" do
        event_giveaway = EventGiveaway.create! valid_attributes
        put :update, {:id => event_giveaway.to_param, :event_giveaway => valid_attributes}, valid_session
        response.should redirect_to(event_giveaway)
      end
    end

    describe "with invalid params" do
      it "assigns the event_giveaway as @event_giveaway" do
        event_giveaway = EventGiveaway.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventGiveaway.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_giveaway.to_param, :event_giveaway => {  }}, valid_session
        assigns(:event_giveaway).should eq(event_giveaway)
      end

      it "re-renders the 'edit' template" do
        event_giveaway = EventGiveaway.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventGiveaway.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_giveaway.to_param, :event_giveaway => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event_giveaway" do
      event_giveaway = EventGiveaway.create! valid_attributes
      expect {
        delete :destroy, {:id => event_giveaway.to_param}, valid_session
      }.to change(EventGiveaway, :count).by(-1)
    end

    it "redirects to the event_giveaways list" do
      event_giveaway = EventGiveaway.create! valid_attributes
      delete :destroy, {:id => event_giveaway.to_param}, valid_session
      response.should redirect_to(event_giveaways_url)
    end
  end

end
